# Generated by Django 5.2.7 on 2025-11-04 00:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Facility name', max_length=200)),
                ('type', models.CharField(choices=[('hospital', 'Hospital'), ('fire_station', 'Fire Station'), ('police_station', 'Police Station'), ('ambulance_base', 'Ambulance Base')], db_index=True, max_length=32)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('properties', models.JSONField(blank=True, default=dict, help_text='Additional metadata')),
                ('geom', django.contrib.gis.db.models.fields.PointField(help_text='Facility location (WGS84)', srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Emergency Facility',
                'verbose_name_plural': 'Emergency Facilities',
                'db_table': 'services_emergencyfacility',
                'ordering': ['name'],
                'indexes': [
                    models.Index(fields=['type', 'created_at'], name='services_em_type_ed1175_idx'),
                ],
            },
        ),
    ]
