# Generated by Django 5.2.7 on 2025-11-04 00:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyFacility',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('type', models.CharField(choices=[('hospital', 'Hospital'), ('fire_station', 'Fire Station'), ('police_station', 'Police Station'), ('ambulance_base', 'Ambulance Base')], max_length=32)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('website', models.TextField(blank=True, null=True)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Emergency Facility',
                'verbose_name_plural': 'Emergency Facilities',
                'db_table': 'emergency_facility',
                'managed': False,
            },
        ),
    ]
