# Generated by Django 5.2.7 on 2025-11-04 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergencyfacility',
            options={'ordering': ['name'], 'verbose_name': 'Emergency Facility', 'verbose_name_plural': 'Emergency Facilities'},
        ),
    ]
