# Generated by Django 5.2.7 on 2025-11-04 01:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_emergencyfacility_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyfacility',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='emergencyfacility',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='emergencyfacility',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(help_text='Facility location (WGS84)', srid=4326),
        ),
        migrations.AlterField(
            model_name='emergencyfacility',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='emergencyfacility',
            name='name',
            field=models.CharField(help_text='Facility name', max_length=200),
        ),
        migrations.AlterField(
            model_name='emergencyfacility',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='emergencyfacility',
            name='properties',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata'),
        ),
        migrations.AlterField(
            model_name='emergencyfacility',
            name='type',
            field=models.CharField(choices=[('hospital', 'Hospital'), ('fire_station', 'Fire Station'), ('police_station', 'Police Station'), ('ambulance_base', 'Ambulance Base')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='emergencyfacility',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='emergencyfacility',
            name='website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name='emergencyfacility',
            index=models.Index(fields=['type', 'created_at'], name='services_em_type_ed1175_idx'),
        ),
        migrations.AlterModelTable(
            name='emergencyfacility',
            table='services_emergencyfacility',
        ),
    ]
