# Generated by Django 5.2.7 on 2025-11-04 00:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(blank=True, help_text='Original source identifier', max_length=100, null=True)),
                ('name_en', models.CharField(db_index=True, help_text='County name in English', max_length=100)),
                ('name_local', models.CharField(blank=True, help_text='County name in local language', max_length=100, null=True)),
                ('iso_code', models.CharField(blank=True, help_text='ISO 3166-2 code', max_length=10, null=True, unique=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(help_text='County boundary (WGS84)', srid=4326)),
            ],
            options={
                'verbose_name': 'County',
                'verbose_name_plural': 'Counties',
                'db_table': 'boundaries_county',
                'ordering': ['name_en'],
            },
        ),
    ]
