# Generated by Django 5.2.7 on 2025-11-04 00:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('source_id', models.TextField(blank=True, null=True)),
                ('name_en', models.TextField()),
                ('name_local', models.TextField(blank=True, null=True)),
                ('iso_code', models.TextField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'County',
                'verbose_name_plural': 'Counties',
                'db_table': 'admin_counties',
                'managed': False,
            },
        ),
    ]
