# Generated by Django 5.2.7 on 2025-11-04 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boundaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='county',
            options={'ordering': ['name_en'], 'verbose_name': 'County', 'verbose_name_plural': 'Counties'},
        ),
    ]
