# Generated by Django 5.2.7 on 2025-11-04 01:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundaries', '0002_alter_county_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(help_text='County boundary (WGS84)', srid=4326),
        ),
        migrations.AlterField(
            model_name='county',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='county',
            name='iso_code',
            field=models.CharField(blank=True, help_text='ISO 3166-2 code', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='county',
            name='name_en',
            field=models.CharField(db_index=True, help_text='County name in English', max_length=100),
        ),
        migrations.AlterField(
            model_name='county',
            name='name_local',
            field=models.CharField(blank=True, help_text='County name in local language', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='county',
            name='source_id',
            field=models.CharField(blank=True, help_text='Original source identifier', max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='county',
            table='boundaries_county',
        ),
    ]
