# Generated by Django 6.0 on 2025-12-05 13:36

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatcherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_number', models.CharField(blank=True, max_length=20)),
                ('is_on_duty', models.BooleanField(default=False)),
                ('shift_start', models.DateTimeField(blank=True, null=True)),
                ('shift_end', models.DateTimeField(blank=True, null=True)),
                ('incidents_handled', models.PositiveIntegerField(default=0)),
                ('notification_preferences', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispatcher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispatcher Profile',
                'verbose_name_plural': 'Dispatcher Profiles',
                'db_table': 'incidents_dispatcherprofile',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_number', models.CharField(editable=False, help_text='Unique incident reference number', max_length=20, unique=True)),
                ('incident_type', models.CharField(choices=[('fire', 'Fire'), ('medical', 'Medical Emergency'), ('police', 'Police'), ('traffic', 'Traffic Accident'), ('multi_agency', 'Multi-Agency'), ('hazmat', 'Hazardous Materials'), ('rescue', 'Search & Rescue'), ('other', 'Other')], db_index=True, max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('en_route', 'En Route'), ('on_scene', 'On Scene'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=15)),
                ('title', models.CharField(help_text='Brief incident description', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed incident description')),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Incident location (WGS84)', srid=4326)),
                ('address', models.CharField(blank=True, help_text='Address of incident', max_length=500)),
                ('reporter_name', models.CharField(blank=True, max_length=100)),
                ('reporter_phone', models.CharField(blank=True, max_length=20)),
                ('reported_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('properties', models.JSONField(blank=True, default=dict, help_text='Additional metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispatcher', models.ForeignKey(blank=True, help_text='Dispatcher who handled this incident', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'db_table': 'incidents_incident',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sign', models.CharField(help_text='Radio call sign (e.g., AMB-01, FIRE-03)', max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('ambulance', 'Ambulance'), ('fire_truck', 'Fire Truck'), ('police_car', 'Police Car'), ('rescue_unit', 'Rescue Unit'), ('hazmat_unit', 'Hazmat Unit'), ('command_vehicle', 'Command Vehicle'), ('helicopter', 'Helicopter'), ('boat', 'Rescue Boat')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('dispatched', 'Dispatched'), ('en_route', 'En Route'), ('on_scene', 'On Scene'), ('returning', 'Returning'), ('out_of_service', 'Out of Service'), ('maintenance', 'Under Maintenance')], db_index=True, default='available', max_length=15)),
                ('registration', models.CharField(blank=True, help_text='Vehicle registration number', max_length=20)),
                ('make_model', models.CharField(blank=True, help_text='Vehicle make and model', max_length=100)),
                ('capacity', models.PositiveIntegerField(default=2, help_text='Crew capacity')),
                ('equipment', models.JSONField(blank=True, default=list, help_text='List of equipment on vehicle')),
                ('capabilities', models.JSONField(blank=True, default=list, help_text='Special capabilities (e.g., ALS, hazmat)')),
                ('current_location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Current vehicle location (WGS84)', null=True, srid=4326)),
                ('location_updated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_incident', models.ForeignKey(blank=True, help_text='Currently assigned incident', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles', to='incidents.incident')),
                ('home_station', models.ForeignKey(blank=True, help_text='Home station/facility', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='facilities.emergencyfacility')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'db_table': 'incidents_vehicle',
                'ordering': ['call_sign'],
            },
        ),
        migrations.CreateModel(
            name='VehicleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('en_route_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('route_geometry', models.JSONField(blank=True, help_text='GeoJSON LineString of calculated route', null=True)),
                ('route_distance_m', models.FloatField(blank=True, help_text='Route distance in meters', null=True)),
                ('route_duration_s', models.FloatField(blank=True, help_text='Estimated route duration in seconds', null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_assignments', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='incidents.incident')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='incidents.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Assignment',
                'verbose_name_plural': 'Vehicle Assignments',
                'db_table': 'incidents_vehicleassignment',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status', 'priority', 'reported_at'], name='incidents_i_status_0fef76_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['incident_type', 'status'], name='incidents_i_inciden_b0a029_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vehicle_type', 'status'], name='incidents_v_vehicle_941e6d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vehicleassignment',
            unique_together={('incident', 'vehicle', 'assigned_at')},
        ),
    ]
